name = "Odin"
version = "0.0.1"
author = "William"
display-name = "Odin"
description = "add odinglang Support to lapce editor"
wasm = "bin/odin.wasm"

[activation]
language = ["odin"]
workspace-contains = []

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."lsp.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
