name = "Odin"
version = "0.0.0"
author = "William"
display-name = "<Odilang support"
description = "add odinglang Support to lapce"
wasm = "bin/<OdinSupport>.wasm"

[activation]
language = []
workspace-contains = []

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."lsp.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
